### ISSUE TITLE
Implementations to-do

### ISSUE THREAD

**Issue by nappyboyradio** [k1d4/124-assignment#2]
**_Don't forget to unit-test at every stage!_**

- [ ] Learn proper use of random-number generators
- [ ] Implement weighted undirected graphs

- [ ] Implement generator for 1-dim random complete graphs
- [ ] Implement generator for 2-dim random complete graphs
- [ ] Implement generator for 3-dim random complete graphs
- [ ] Implement generator for 4-dim random complete graphs
